downloads: ~/.ansible-downloads/
# configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
# configure_dock: false
# dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
# dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5
homebrew_installed_packages:
  - ansible
  - bat
  - chezmoi
  - curl
  - exa
  - fd
  - findutils
  - fontconfig
  - fzf
  - gh
  - git
  - git-lfs
  - gpg
  - highway
  - just
  - k9s
  - kubernetes-cli
  - yamlfmt
  - lazydocker
  - lazygit
  - minikube
  - neovim
  - python@3.11
  - ranger
  - ripgrep
  - starship
  - taskwarrior-tui
  - tmux
  - tree
  - wget
  - wrk
  - zoxide
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - github/gh
homebrew_cask_apps:
  - alacritty
  - alfred
  - authy
  - chromedriver
  - docker
  - firefox
  - font-fira-code-nerd-font
  - google-chrome
  - microsoft-edge
  - notion
  - slack

# See `geerlingguy.mas` role documentation for usage instructions.
# mas_email: ""
# mas_installed_apps: []
# mas_password: ""

# osx_script: "~/.osx --no-restart"
