---
- name: OSX Setup
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  vars_prompt:
    - name: email
      prompt: What's your email?
      default: axelyung@gmail.com
      private: false
    - name: ssh_key_passphrase
      prompt: SSH key passphrase? (leave blank to skip)
      private: true
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/*.yml"
      tags: [always]
  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: [pkgs, xcode]
    - role: geerlingguy.mac.homebrew
      tags: [pkgs, homebrew]
  tasks:
    - name: Setup
      ansible.builtin.import_tasks: tasks/setup.yml
      tags: [setup]
    - name: OSX
      ansible.builtin.import_tasks: tasks/osx.yml
      tags: [osx]
    - name: Sudoers
      ansible.builtin.import_tasks: tasks/sudoers.yml
      tags: [sudoers]
    - name: Terminfo
      ansible.builtin.import_tasks: tasks/terminfo.yml
      tags: [terminfo]
    - name: Crypto
      ansible.builtin.import_tasks: tasks/crypto.yml
      tags: [crypto]
    - name: AppStore
      ansible.builtin.import_tasks: tasks/mas.yml
      tags: [pkgs, mas]
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: [dotfiles]
    - name: Wallpaper
      ansible.builtin.import_tasks: tasks/wallpaper.yml
      tags: [wallpaper]
    - name: Asdf
      ansible.builtin.import_tasks: tasks/asdf.yml
      tags: [pkgs, asdf]
