---
- name: OSX Setup
  hosts: 127.0.0.1
  connection: local
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  gather_facts: true

  vars_files:
    - default.config.yml

  vars_prompt:
    - name: email
      prompt: What's your email?
      default: axelyung@gmail.com
      private: false
    - name: gh_username
      prompt: What's your GitHub username?
      default: axelyung
      private: false
    - name: ssh_key_passphrase
      prompt: SSH key passphrase? (leave blank to skip)
      private: true

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: [always]

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: [pkgs, xcode]
    - role: geerlingguy.mac.homebrew
      tags: [pkgs, homebrew]
  # - role: geerlingguy.mac.mas
  # when: mas_installed_apps or mas_installed_app_ids
  # tags: ['mas']
  # - role: geerlingguy.mac.dock
  # when: configure_dock
  # tags: ['dock']

  tasks:
    - name: Setup
      ansible.builtin.import_tasks: tasks/setup.yml
      tags: [setup]
    - name: Copy custom sudoers configuration
      tags: [sudoers]
      copy:
        src: "{{ playbook_dir }}/files/sudoers/custom"
        dest: /private/etc/sudoers.d/custom
        mode: 0440
        validate: visudo -cf %s
      become: yes
    #- name: Sudoers
      #ansible.builtin.import_tasks: tasks/sudoers.yml
      #tags: [sudoers]
    - name: Terminfo
      with_items: "{{ query('fileglob', 'terminfo/*') }}"
      ansible.builtin.include_tasks:
        file: tasks/terminfo.yml
        apply:
          tags: [terminfo]
      tags: [terminfo]
    - name: Crypto
      ansible.builtin.import_tasks: tasks/crypto.yml
      tags: [crypto]
    - name: Node
      ansible.builtin.import_tasks: tasks/node.yml
      tags: [pkgs, node]
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: [dotfiles]
