- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    type: ed25519
    passphrase: "{{ ssh_key_passphrase }}"
    comment: "{{ email }}"
