- name: Create Code directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Code/axelyung"
    state: directory
    mode: "0755"
- name: Create Screenshots directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Pictures/Screenshots"
    state: directory
    mode: "0755"
