---
- name: Copy custom sudoers configuration
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/sudoers/custom"
    dest: /private/etc/sudoers.d/custom
    mode: "0440"
    validate: visudo -scf %s
    backup: true
